{% set name = "hellocry" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6e1f62e76e2600d7397c73a74b3045ff3e7741b00478a374fecf7709bd79d13c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - hellocry

about:
  home: "https://pypi.org/project/hellocry/0.0.1/#description"
  license: MIT
  license_family: OTHER
  license_file: 
  summary: "Test for crystal repository"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - acossard
